if: type = pull_request

jobs:
  include:

  - stage: test
    before_script:
    - echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
    - docker pull samseedsoftwire/todo-app-test:latest
    - docker build --target test --tag samseedsoftwire/todo-app-test:latest .
    script:
    - docker run samseedsoftwire/todo-app-test:latest tests_unit -rA
    - docker run samseedsoftwire/todo-app-test:latest tests_integration -rA
    - docker run -e AUTH_PARAMS_KEY=$AUTH_PARAMS_KEY -e AUTH_PARAMS_TOKEN=$AUTH_PARAMS_TOKEN -e BOARD_ID=$BOARD_ID -e FLASK_APP=$FLASK_APP -e FLASK_ENV=$FLASK_ENV samseedsoftwire/todo-app-test:latest tests_e2e -rA
    after_success:
    - docker tag samseedsoftwire/todo-app-test:latest samseedsoftwire/todo-app-test:$TRAVIS_COMMIT
    - docker push samseedsoftwire/todo-app-test:latest
    - docker push samseedsoftwire/todo-app-test:$TRAVIS_COMMIT

  - stage: publish
    before_script:
    - echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
    - docker pull samseedsoftwire/todo-app-prod:latest
    - docker build --target prod --cache-from samseedsoftwire/todo-app-prod:latest .
    - docker tag samseedsoftwire/todo-app-prod:latest samseedsoftwire/todo-app-prod:$TRAVIS_COMMIT
    script:
    - docker push samseedsoftwire/todo-app-prod:latest
    - docker push samseedsoftwire/todo-app-prod:$TRAVIS_COMMIT

  - stage: deploy
    before_script:
    - echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
    - docker pull samseedsoftwire/todo-app-prod:latest
    script:
    - docker build --target prod --cache-from samseedsoftwire/todo-app-prod:latest .
    after_success:
    - docker tag samseedsoftwire/todo-app-prod:latest registry.heroku.com/$HEROKU_APP_NAME/web
    before_deploy:
    - heroku container:login --verbose
    deploy:
      provider: script
      script: bash ./deploy_prod.sh
      on:
        branch: module_8 # TODO: update this once I've sorted out master branch
      skip_cleanup: true
    after_deploy:
    - curl "https://$HEROKU_APP_NAME.herokuapp.com/"

services:
- docker

env:
  global:

  ### Trello ####
  # AUTH_PARAMS_KEY
  - secure: "m7rLT6c8Go2Gd9m9uAZhvtUUQloLh1fHRp3846Upk6L32DAJ3G9yzKx/dMJ+w4X009QvGLaJp/yeAQw8AnKRPVNl+pZcdMCOF8E2NUtXnheHdBwLKUaqJdyMNU9sC1dytr3FIBS4e+gPBGArtjiMMqZzcbrDogqRbW/KRFoEpfekuW74u6JpeSTNN02lr+oiPcU2z8t0SNo6FB7YQMx0e/SQgK6wrKyavqsyhU3DzMZlpu790wpeuR1oQYtEX604NE68zt11UqLMJp87qmCXC62gr1Y2s7uqoWphtj6cLLBwAhHPi/VAgjIBuLfdqDU1nlfddRM/8fuSZo0Pspvao4C32U4OFZPCRt9DapXenkH16dj01NEAwrtDk8VHWkGmRLscZo95KMOFZNtzlwTzTaLYiHwUbf2+V9Q9h+iRRbonfjAwPGZIXlZIZLi324NrtwewPE7v41ml9jlSRli6i53WMVAJreCOc9rj6GpQt0a+y8IEOl0yqJcpFfgyITeHbTYiEq0pClVaJk8adi6DFeGFp/KGYWW3h5B+8ZyPTGgwS/fbbZyKU17cHefVI+krFXuzo5nmqWS7TzrGZBDp7yp4TQ3EvtL1NTF+X5TY2GCyHakqjkSTbOLxXDmf8sBwhHeQIAMP0LeGKu9R3+KhuOO0qLelO9WDmp0nBOb42uk="
  # AUTH_PARAMS_TOKEN
  - secure: "qnaHGpxllG0W0LAqiviDlKARgg1yxD3iN1h2tX8DjboQuHkyeXP9ugrnkdO4zkU4rKYaTlG8zK3YCJOrVWfowm8duyl7jU4IubT7CzflOhZXMdho5OFR6sMqtCyNLcDEBaLvCxmWDyl4f6SzRil2UWutPY/bX0MOZYOurTuOYcgy/fwPZgXlQHQLja6eNKEwZ3QP6a2BC9jyIImoi97I5mkp9QM6k1Swp4qBIdjVKMs2OJWdIIn41ISv2b8AtBXi9DCfO38TgCGPbgsJoOd9Tig609MVG3xEXS8arVc9qR3FfwewNkSZxdr+qRp1NqDQUpqagK5f6trBqpUZ0ovGDvC2nBVUuaufr8icyX15fIdJ8EWnhM9ekN/g0Sf87LlwaC2c/ijQF/Gwq4My4uINdjWqGiePE2ZKBSmUnEZJi1Cr/pTPxkEyIcilLVsSX0Jhh1iEy0+vyj2kClmIw7TnXfXEbdjML4SwKkHE6rjtsNSdiWruaEgsfVTQe7sCIB4QGrrJ/rjP2W+APyY/fXYHua5UJB2JGC7QZuZZdpjAY5MARSLUL98Sg7LC0bVXJTezq8qZM05xTKFNo/36sApiIevL2T3D4RuaiTa36Cw1g7iLUhrGng6OOqauwIqEi7UWuDIaPzQGBVbxWgr/yGfCQqiBx5a6HPljWgaJd9IYC1o="
  # BOARD_ID
  - secure: "qXjPKc/8rd+QPzz/dMd0xo7zuisiPrrqE6wRMVHWpe4V8DbVOvi7n0u6fI3HryHstFKLDnqQIBXuHMQa7KcruAQmIn1X/P27AmO5138SbZKlCdyTcVtJr/8MY4Azyn1cKsHQASVVgSRz9stPrpLl7pAQzDrWOa76x3LoS/9cMpW05ANTCqGhEw2bIdEFwSxjYgQHLpCY2lUYJKP3+nRG9oM5Ma7GaoX/8br60rH7myp9lB63alu48jLYC8/l/D4zFa7BBVU2XvHepe7yU89RWMoDWcse4MFjkcUN23Fu4Ap/qEkaivI8M7sxvqdqgKcKmspJ3/YebmLlpjC3slTVEEtFxsf/MPb8HDscIBdvoQ10wKW8MhtTvt4dc2BkIEY9Yw6YuM4+Xns0u9A5wNZIinOMm1iwBf0Uplw5Vz0e+XyXObCJC4rUWy5knk1WPArnspEEejAQ556EFSYqXCHM/D5iHX8MfZDs4ZTBcY4gWJOC8wrTc3Ny84DFfYpfz1Tx7LNGFHR0H+Ri4QyBBLjyPcXbCtjTIKgnKG2AvVfElFVzZ30TXKjLZqxQlBIxV8DFa02rWa0F/i0pipZwZqNnpIIEwW8LqVNgMr09Rv2TfWaKiN79FYtwuE3uWPUFn9nHNJwUgpBToS9r2OarxAjDY7YwVevdmwXLJbAtsTlsgaM="

  ### Docker ###
  # DOCKER_USERNAME
  - DOCKER_USERNAME=samseedsoftwire
  # DOCKER_TOKEN
  - secure: "Unpltfd/dDkhWPM7aHMzQvLn48HUyQDI1yNZjCQ59oaSNxRugzcIhiIgi8VUMJ2YdAtZWl2+Xs5AcLkvEngWAokwlBGHoDb8fGKIjWaYPUjuR/D92VnMAgcZXBgRDYTpoBbUOjs5YIHz1PgDLt2RV1RxlDqBfadUy7qMuJ8h2wjP4VFSdctQ5luiwIlvGS2rKtqRyX/fI31ZRDFAP80T3nVRtp8iGezsCbGTBoYtCBtNzK2bU4E0gED33Zd6wo+4Q+1uB5QyfYX7NIDixcnjIjCrTKOXpMzYKhFy9HLgKtm79nHDgUHL+zywAdqjwV6vE61egIUGH7m86FFNgvyJK9c0kN1Pcf7NiST5XFIwyi7Y86ji0uOS40FuosOAxgVY42jyRdNhDkpS4m4CA2bcO6FVhbstroIilw6wAtlVCfg0rJyqgg+C+UCrsdQZohjFhge3wupMPlT3vVlGJbXKtxIdOySaM5K1FK1P8hEQMFKX1N12Qzl6AMVVMxq+7wlED9KohM2/Yt+tETdy9AldeVO7zHSVGUFBSGQ/5h+hOUWAT5rJH8TVnkTR2dLdtDiVjlWHPjSBS89lPk7bpN9gvQzihBrcPQ3bzWFHr+4xrr6p7IyUL9MB3Rh/AC7IkMZZvL/ygQfExp/uXYE8kMIxVMzOJC7zuUpVLOagheqyq28="

  ### Flask ###
  - FLASK_APP=./application/app
  - FLASK_ENV=development

  ### Heroku ###
  # HEROKU_API_KEY (Heroku long-lasting authorisation token)
  - secure: "GTxM+8rCszqd6VQ/rb24cmRPfY9FjBn4Te+AFGWq8J9ZxsdmCvVBMJ0AXUsIPXgghLu6gQryjjkJwUcsi9KL7Kcm3YJuqHzgTNCqgXw+VcAqX2vZwMTKFUQZR2reBQ5lqEDCq3th35qdd4BQi21UWzvKpkqDSEukLbHF/gJRdP+2h5TbU80SM7U60RQST3pFMuLfr0CKxZWgZ+VuyXoUmlt90UNjLmiU/khGEn90/aAjSGbFna75g8E+6IzWu/iGnlRQNZoyHNlI/a4o2MNldvGneUmiB5yrOhKciKzWodwwLHewoevOA1sZi71oInb3N1Px5L2bsRsUZZ4hcWbSYGoInSI9GsawAQ88RkREZ8aKD0LZVys9EHXf8sFM1IFBb2CdgH98EpH5wnd5exUSuWuGbJNajoJrOak5Wk9tD/r5fZJ6bQUSOLSyHdpUuwFDO1vyY5zqzq4nyyMJZpsSb09LJfIjnbfWLzL7bQ46wBXVkVOxDJvtH96017U3Ysf7aGFXC3z1lvU2XWWiG+E0WFa2KlS+xhG2V3hgVzmD8HwW3+u2B1VxVE5cFVH0I5yZ1blmj45TwsAcXMaXlGf8ltP4eAxvDRso7Mzna/wWVhRmmUYBKytdYYKsa1Su7lzfezF5xJb12k9AFb4H+q/tw7QDQ2r4LUftV8nuyQ2ZtWA="
  # HEROKU_APP_NAME
  - HEROKU_APP_NAME=still-spire-18415

notifications:
  slack:
    secure: "bk8pIUB45EdlSUDHVsMif7N6QnbsWPc5gHYOXWA7KuCYbFzwME6uinXghoXijIUexhJ1l6X22AXQoxKOGCKQgBBFc4U+R2EeGikIY6d/k2k14j1W6L13cdgJ42mQphDtWUB15yObZk1Nlk94PoFbIech1EIc6YUkzeHG27CNiLGmVSSFXVn29qIzUF0eJhln6YelHJXKFWMIoyJJUHx599IE/A9T2Cu2jNwjPMyvfcyHwCJ+Pk2Yl7o9QJs7d8P+enZjRxOBT6tFDiGZYfcK2HlvwJaD3s0ZFJHpC9+PDDo2GVTa9RhOop3ScAZup10iiyAzyCa36w6/Rqqyj4tK2fZJpIv/L7pHXV85zsrBBIsh3bHt2zBVxXKcrlfYJ7XyvYoPi2yPuD6A6ARFCrcfmTyfePhdvjL3MaIHXbZcElAiH8oBbPJ2kj+3asgGjTAUWdnfF/o6ozlfD5/CVhRHNY0KmqDMqjJkXcLzFZOUIraK2SaC5oQmfoSj+CauDsxKt3Lk/pmzR9TdZfh07ce99GYx+sS2umSxriDLib9oMinpwNDWO487vTArjTKd0DJrgdZ1+6S8lZtgDsXHD/1MNzUjNAz7U+iYtbSxaiR/8LQ5F16hm0xOC+54htnAjpWgsD5numhzEUj1SpGgKKtAo1FoBcIs+26ARItBvnJFVh4="
