if: type = pull_request

services:
- docker

script:
- echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
- docker build --target test --tag todo-app-test .
# Run tests.
- docker run todo-app-test tests_unit -rA
- docker run todo-app-test tests_integration -rA
- docker run -e AUTH_PARAMS_KEY=$AUTH_PARAMS_KEY -e AUTH_PARAMS_TOKEN=$AUTH_PARAMS_TOKEN -e BOARD_ID=$BOARD_ID -e FLASK_APP=$FLASK_APP -e FLASK_ENV=$FLASK_ENV todo-app-test tests_e2e -rA

env:
  global:

  ### Trello ####
  # AUTH_PARAMS_KEY
  - secure: SRMdJhHoQTQmmBXxoB8BaCnglfWMgtBL5mPPjB8ZJULR9KlMwIOCg8hTc10vOSfPnJXWFohs43eENRc25ebd91RBZEoYr5GzBC1oDQvpBFSEz8wNVhMTFge97Vasd5zYoQH3H9tWcqu1oxxZpt+7mcP5/bUsV08DcRApawLPiLVyq4+YScGB8KLLuane8+M2PIHwJAjy/VwCTsXQuU69AEuihAimVdsFIMdukfT/IzSbSMGn2ZNzGHjHBKl/K+nzsBZ2MLwOdp8Xted7wFLMlbZ8bOHUxYTR47uJirZEq+AZdu7xXGbdAhykKlKWaoq19ymo1KgC8pMTJUfObkqoAN3ejURNd2fOe7VM47vuLPclNyh3WarVWF/anKpR23nz9spcnI2PMcsneQ8Ev0cUHNKaMI2R0QFOrocxhlnkN90zDAGYgmK/8SqQPqYmBlrJCbwslQSTVBsqT3GfgaepPke5j+jkIr7aDnB86oGtW8ziWa8xje9pCZuctGX5s17khM6W6goR7NQqKR4+HGyyVp23635yrB3HAzvclO8ySYKp7BZ0VAZMqBb0HjS0KrMbEoogcA/fy888Kstkq3sOer1jXLTYilPoU6gmszT0M153RYG/Xl04Icx0yJQlULk0O8rW4DwKe8A9epKcGaGm00zLtkRmhNypHgJ+fX6/W0o=
  # AUTH_PARAMS_TOKEN
  - secure: AVQXvkkFJVcNlVcBvALFUjl4gzvl0MVpCAhFptt8xLYQ8suqJNU9xaYeYFlSGn6uVNIOWgonyutvkcF5Akx/3/VAHe2S+eQju31yy84xN55cZX00opiODBTv6t51Bcdv8+YfwzRJ9qrDc4dALyee2jhyNYRq4YkcMqLDV2stnM62KgUlFASMIKu5ri+O8DxcNOXPWxG7wjcs0aWSf37NAkKZm6jl1s/4DceTLr/RyTPequlZv8mYQoeQqexekhunwEdNsccmpIi8sumBsvCvVwPHU8Kk84QEl5KX+BgV/l5BJNWum+otwyzawM6gTtz7jJvAxFkZqZ1ngfJ3/A4hz/aswaTXZrh2TQzCQ+WMTv88Xeg3MjSNOp0W59g1ORkCoryh5IWiQSvXPqAv4oMLaQU7SJaRraZuR6KJnR4IlLf2rWct+wnNwiajQkl/MHvTDghQhfDGUf/x1X8/ZqVPS6IX1xmQ3j4+PEUf+9Rf/5Z43mJuXPtq15uxoWNqiqFyKgFFKVWzCiv0Xu59EvBwx3Okda/YFUzG5oj5yxDhpiqE256z1rTLL4KT0nRw/50w2gGx0wK9gU/s/ykO7V7693PlHeKbaxQvK8BCDOQFQThlxcHG/3wZ+DnIDXoF8pU7ObOb7I1wYK7aKk1lj3RmzGA/nsprmQjjHsDVVxea4DY=
  # BOARD_ID
  - secure: Ow2iZxceWOJrp5Cg6bvkbz9JPzjx/1wyWa+xifsKCu81Gdd2Uz8RI8P0YJVkJTUKu4n5t0Rx/hrg9MvfkTTlvIsPZZABTbHq3UHu5Y7vTz1P6tKhcW7P3blA9xrO/xd3HYYpDVhUaClrE8WZXeXDXo6eacjEDUgBwusmWpHafZI2TkMJ93l8RVus8zA1A6RGx7n3zp8UerlZ1j4Qlk7gNgxDUMr4XKNhtZwpf84zmqSL6Kd83e55OPuMpeJkRAu45Abh8a3unWljdTjEL5cxYn6Yp7QdvqQu9tRdQNZY0FbP5JOuVkdSaas+SA9lto2CsyVvDq5SIs584NY6jRKm1Po2QXpqUrjgXH8XNp3A4LU2kEAeUH4PRrFiCAUjgmKfJvAUCtnPvyfAGh973bDIqFgSSFtn3lq+BcHSDoaPw2POFcgp0kBtMZ8ePyahUPdcaPtiYQ9ARCiZhLV5AQYBtmYFs+o52RPrgviuqGeOK01H+JGcEBHKDk7mNEl2VTS8TxIx1/41oVm0Wm13ZLVow2P7mXYsrqjHkGkei1Eglr3TwDD/ZeR5yYcwXWfatzzxs58fRpWObNBQgSep3vhEBKGBb5NDDHkroj1d0cb4BhcD9ANmbSEU5ib26IVqzKKp1C5JpQ9V50ZfQnGkzm/sn3l7+G8g/I76kzcbKEyOjiI=

  ### Docker ###
  # DOCKER_USERNAME
  - DOCKER_USERNAME=samseedsoftwire
  # DOCKER_TOKEN
  - secure: BrhIjIA+zb3Lx+SyoaFjdC8cQ765qgTc4R1rdbyMs+E7gniebEci2sqpDrCponzn6NA5doBnxl58tDqpYKN6/SFRe8aE0DD9vmULCMyRyGhiQZGAAoy+vxMtg6TxrvwsTeDaWFtZS3TN+ZhdBtHAC32O7zZMEBEfKjTMujiOZTcfuFpHUno0G3gdg+OiScbKe1ACcjKYgc6oQ+nOzgAQKF5bz/eDz8UBcbJ1zmV/LfwHVn2VrJbT4W/g/p/gmnyrltGngf9dV0xVby2T1TlH52RdTFMxX71+V47uPMtK1bxXsV9g43nE3mp2jUXFqnUAvo+7GaHWEBseY+IAOsrESvEYw2Q1CKmtUtuxWOyuC+PsArlPamIg5Dyxhtxu5aMeJRDITTcIQZKPDDbEdiUw+eFqPhKZs5U3Anpa6uFMFTCyirGHYIx12kG2ekGNoB8Ss4EnYunTf5ZgQfPhbp7kPQ6yKsdgKiCfJi0qx1yRiZ6QVIQqc8zTbGFEEewhHGEHzE0a1Vb9fVd3b+7MuYXcfZRXOSwJFD7ZGcNEFY4d3lezQix5gX9X2fhEt/p32Fnxg14ZwNyiIrx0QTg+aLQV/qcPga1tRnrx5Gdfh5uSghzGOMvIf9dZLRGFjPIOzAPj09Ag4nTpOaBhenXpiKHCFwYnv5cetqgdgHjp3Gw4m5k=

  ### Flask ###
  - FLASK_APP=./application/app
  - FLASK_ENV=development

notifications:
  slack:
    secure: kbpZKkB4tjQr1AE8YJTBuEBaBP5HhvJ8OeL4UE02DxMECwBv8FKeSB/aW7SSSbGq72PcIbGlVXeTP86tAJnkoqrbu8OdZEGyOxg1By4wUxWHSwZtr4R7EKZRWMQppxq8r3O8lukdn/gB+72E2bzTCCISEcehBRbdtNcEEBtCbH+kZ1YJF1v7GEBNYBnU8D5dfFvlvUDskJpoRefZgRb756CpqsPWiXiKVaxDc/StDvaMmLKVwMrX3okHTojOmdExgnudUhqcmr6OVOEl2kwjzR0ZrS5UiyTc4e5zeo1rDRTYhXOiiFjzm1EISogtAmpAZYW0Aq0mCIwHWSOcozcGIYaNL1cytcLijqf+L0KKdtL8umKA3Kjcp47ZmZtgXMQHqD2UnknKq4y+1aPLBIyiYzoKN4yzOKwJNCjDX7m51Gc0yH8KeQ8aVk6H93DKFWwxpQclRIR0pTr2juaawG34EifRtLaD3iEnIAaix7PHrl9I/y68FFT07jr0XXUvMwu0M9wbbo94UQ4mANd1eqWF8zOyzPk03MtazS7E6dN2abqdua4xvPNEbMY7gfqUOcC2MjREMAUzdhJc5WRRKi3U729AiAgj+QVgwttzLCaAJNRqXOMi5cpIFyXc6Sysu51k/AKAynAyFl1Xyz2kDP798ugB2PvLNamuwHbZRJfu+N0=