if: type = pull_request

jobs:
  include:

  - stage: test
    before_script:
    - echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
    - docker pull samseedsoftwire/todo-app-test:latest
    - docker build --target test --tag samseedsoftwire/todo-app-test:latest .
    script:
    - docker run samseedsoftwire/todo-app-test:latest "tests/tests_unit" -rA
    - docker run samseedsoftwire/todo-app-test:latest "tests/tests_integration" -rA
    - docker run -e COSMOS_USERNAME=$COSMOS_USERNAME -e COSMOS_PASSWORD=$COSMOS_PASSWORD -e COSMOS_HOST=$COSMOS_HOST -e COSMOS_PORT=$COSMOS_PORT -e COSMOS_TODO_APP_DATABASE=$COSMOS_TODO_APP_DATABASE -e FLASK_APP=$FLASK_APP -e FLASK_ENV=$FLASK_ENV samseedsoftwire/todo-app-test:latest "tests/tests_e2e" -rA
    after_success:
    - docker tag samseedsoftwire/todo-app-test:latest samseedsoftwire/todo-app-test:$TRAVIS_COMMIT
    - docker push samseedsoftwire/todo-app-test:latest
    - docker push samseedsoftwire/todo-app-test:$TRAVIS_COMMIT

  - stage: publish
    before_script:
    - echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
    - docker build --target prod --tag samseedsoftwire/todo-app-prod:latest .
    - docker tag samseedsoftwire/todo-app-prod:latest samseedsoftwire/todo-app-prod:$TRAVIS_COMMIT
    script:
    - docker push samseedsoftwire/todo-app-prod:latest
    - docker push samseedsoftwire/todo-app-prod:$TRAVIS_COMMIT

  - stage: deploy
    script:
    - skip
    deploy:
      provider: script
      script: bash ./deploy_prod.sh
      skip_cleanup: true
    after_deploy:
    - curl_response=$(curl "http://softwirepilot-samseed-projectexercise.azurewebsites.net/")
    # TODO: cause Travis build to fail if the curl is unsuccessful.
    - if [[ "$curl_response" == *"To-Do App"* ]] || [[ "$curl_response" == *"https://github.com/login/oauth/authorize"* ]]; then echo "Successful curl!"; else >&2 echo "Curl failure :("; return 1; fi

services:
- docker

env:
  global:

  ### Azure ###
  - AZURE_APP_SERVICE_NAME=softwirepilot-samseed-projectexercise

  ### Docker ###
  - DOCKER_USERNAME=samseedsoftwire
  # DOCKER_TOKEN
  - secure: "Unpltfd/dDkhWPM7aHMzQvLn48HUyQDI1yNZjCQ59oaSNxRugzcIhiIgi8VUMJ2YdAtZWl2+Xs5AcLkvEngWAokwlBGHoDb8fGKIjWaYPUjuR/D92VnMAgcZXBgRDYTpoBbUOjs5YIHz1PgDLt2RV1RxlDqBfadUy7qMuJ8h2wjP4VFSdctQ5luiwIlvGS2rKtqRyX/fI31ZRDFAP80T3nVRtp8iGezsCbGTBoYtCBtNzK2bU4E0gED33Zd6wo+4Q+1uB5QyfYX7NIDixcnjIjCrTKOXpMzYKhFy9HLgKtm79nHDgUHL+zywAdqjwV6vE61egIUGH7m86FFNgvyJK9c0kN1Pcf7NiST5XFIwyi7Y86ji0uOS40FuosOAxgVY42jyRdNhDkpS4m4CA2bcO6FVhbstroIilw6wAtlVCfg0rJyqgg+C+UCrsdQZohjFhge3wupMPlT3vVlGJbXKtxIdOySaM5K1FK1P8hEQMFKX1N12Qzl6AMVVMxq+7wlED9KohM2/Yt+tETdy9AldeVO7zHSVGUFBSGQ/5h+hOUWAT5rJH8TVnkTR2dLdtDiVjlWHPjSBS89lPk7bpN9gvQzihBrcPQ3bzWFHr+4xrr6p7IyUL9MB3Rh/AC7IkMZZvL/ygQfExp/uXYE8kMIxVMzOJC7zuUpVLOagheqyq28="

  ### Flask ###
  - FLASK_APP=./application/app
  - FLASK_ENV=development

  ### Heroku ###
  # HEROKU_API_KEY (Heroku long-lasting authorisation token)
  - secure: "GTxM+8rCszqd6VQ/rb24cmRPfY9FjBn4Te+AFGWq8J9ZxsdmCvVBMJ0AXUsIPXgghLu6gQryjjkJwUcsi9KL7Kcm3YJuqHzgTNCqgXw+VcAqX2vZwMTKFUQZR2reBQ5lqEDCq3th35qdd4BQi21UWzvKpkqDSEukLbHF/gJRdP+2h5TbU80SM7U60RQST3pFMuLfr0CKxZWgZ+VuyXoUmlt90UNjLmiU/khGEn90/aAjSGbFna75g8E+6IzWu/iGnlRQNZoyHNlI/a4o2MNldvGneUmiB5yrOhKciKzWodwwLHewoevOA1sZi71oInb3N1Px5L2bsRsUZZ4hcWbSYGoInSI9GsawAQ88RkREZ8aKD0LZVys9EHXf8sFM1IFBb2CdgH98EpH5wnd5exUSuWuGbJNajoJrOak5Wk9tD/r5fZJ6bQUSOLSyHdpUuwFDO1vyY5zqzq4nyyMJZpsSb09LJfIjnbfWLzL7bQ46wBXVkVOxDJvtH96017U3Ysf7aGFXC3z1lvU2XWWiG+E0WFa2KlS+xhG2V3hgVzmD8HwW3+u2B1VxVE5cFVH0I5yZ1blmj45TwsAcXMaXlGf8ltP4eAxvDRso7Mzna/wWVhRmmUYBKytdYYKsa1Su7lzfezF5xJb12k9AFb4H+q/tw7QDQ2r4LUftV8nuyQ2ZtWA="
  # HEROKU_APP_NAME
  - HEROKU_APP_NAME=still-spire-18415

  ### CosmosDB ###
  - COSMOS_USERNAME=softwirepilot-samseed-projectexercise-cosmos
  - COSMOS_HOST=softwirepilot-samseed-projectexercise-cosmos.mongo.cosmos.azure.com
  - COSMOS_PORT=10255
  - COSMOS_TODO_APP_DATABASE=softwirepilot-samseed-projectexercise-mongodb
  # COSMOS_PASSWORD
  - secure: "cP/icx8p3jCBU5gmaPaMe8+kVfVNV/HzpeEJO1Xad1no1XJ2FF1ysiKzYA6Luazdc5Vgkkrx1/5uCLyU+hdQfpt3IzCZq+y6llEhzTJxj2XliCBDvmaYbl7fYfWutHk6WzTO8cRZl6ifXo0WrDOZ7zf9uIcwVU7fWzrPr6IvIZtx7oWL2ihEWfNGLUS8NC2o6T7NB8kmbNfliWGKnzvyiSO7h/iNubJFmdNoOMSzeG5dzbdMesf6HHjBP+Xt/rVggKO8/2sfZ77CXS0XNhnkXZEhKWiXlZxKmpVEu/ns9UdlX6TGUSwefBgD6GDRFhMmCiNNRVcYm9IakyTtyS/D7RDOi9+92k8A5u49oK/kO3qlEObGkR2cVCijhjupcwAE1SFi3EexaPCdpbKFP5GOgtdhBMFePxKRu0CfDBUeB8UCymL1aOjd5GfWoifrdT7PLCfv4S7DRc0VnVoBLeC18qYcAFFPIaiqPd7coVaOz4TRljrBlKuoBOku97GOE0MJWPAeFVCd74U4OAygRljWNlJNunq9a/6vHpPkNpbqZp24AJKAiJJ5N0p9l/NvLk6A74NwF7kiM1ePijZgsOgUxiUlPqUUrvfJMIqNzhx6RcwPeJ2MjzziA12Irg/NYT16RMtvVZ0Z3Ci52p6gZvTRg+8gmXDcgeCzU3SUshAp2Io="

notifications:
  slack:
    secure: "bk8pIUB45EdlSUDHVsMif7N6QnbsWPc5gHYOXWA7KuCYbFzwME6uinXghoXijIUexhJ1l6X22AXQoxKOGCKQgBBFc4U+R2EeGikIY6d/k2k14j1W6L13cdgJ42mQphDtWUB15yObZk1Nlk94PoFbIech1EIc6YUkzeHG27CNiLGmVSSFXVn29qIzUF0eJhln6YelHJXKFWMIoyJJUHx599IE/A9T2Cu2jNwjPMyvfcyHwCJ+Pk2Yl7o9QJs7d8P+enZjRxOBT6tFDiGZYfcK2HlvwJaD3s0ZFJHpC9+PDDo2GVTa9RhOop3ScAZup10iiyAzyCa36w6/Rqqyj4tK2fZJpIv/L7pHXV85zsrBBIsh3bHt2zBVxXKcrlfYJ7XyvYoPi2yPuD6A6ARFCrcfmTyfePhdvjL3MaIHXbZcElAiH8oBbPJ2kj+3asgGjTAUWdnfF/o6ozlfD5/CVhRHNY0KmqDMqjJkXcLzFZOUIraK2SaC5oQmfoSj+CauDsxKt3Lk/pmzR9TdZfh07ce99GYx+sS2umSxriDLib9oMinpwNDWO487vTArjTKd0DJrgdZ1+6S8lZtgDsXHD/1MNzUjNAz7U+iYtbSxaiR/8LQ5F16hm0xOC+54htnAjpWgsD5numhzEUj1SpGgKKtAo1FoBcIs+26ARItBvnJFVh4="
